[profile.default]
src = "src"
out = "out"
libs = ["lib"]

via-ir = true
optimize = true
optimize-runs = 200
evm_version = "paris"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config